name: Integration Tests

on:
  push:
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm --needed base-devel fuse3 sudo

      - name: Setup environment and run integration checks
        run: |
          set -e
          modprobe fuse || true
          mkdir -p /dev/szmelc
          make -C asciibuffer
          make -C shortlog
          make -C syspeek
          make -C gpt
          ./asciibuffer/asciibuffer /dev/szmelc/asciibuffer -f & pid1=$!
          ./shortlog/shortlog /dev/szmelc/shortlog -f & pid2=$!
          ./syspeek/syspeek /dev/szmelc/syspeek -f & pid3=$!
          ./gpt/gpt /dev/szmelc/gpt -f & pid4=$!
          sleep 2
          echo "integration" > /dev/szmelc/shortlog || true
          cat /dev/szmelc/asciibuffer || true
          kill $pid1 $pid2 $pid3 $pid4 || true
          fusermount3 -u /dev/szmelc/asciibuffer || true
          fusermount3 -u /dev/szmelc/shortlog || true
          fusermount3 -u /dev/szmelc/syspeek || true
          fusermount3 -u /dev/szmelc/gpt || true
